//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OursweetGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Job { get; set; }
        public Nullable<int> Age { get; set; }
        public string Towel { get; set; }
        public string Race { get; set; }
        public Nullable<int> HP { get; set; }
        public string Level { get; set; }
        public string Spell { get; set; }
        public string MP { get; set; }
        public Nullable<int> Gold { get; set; }
    }
}
