//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OursweetGame.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameDatabaseEntities : DbContext
    {
        public GameDatabaseEntities()
            : base("name=GameDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<PersonsWeapons> PersonsWeapons { get; set; }
        public virtual DbSet<Weapons> Weapons { get; set; }
        public virtual DbSet<Person> Person { get; set; }
    }
}
